version: "3.8"
services:
  frontend:
    # container_name: frontend
    build: ./frontend
    image: python-frontend:latest
    deploy:
      replicas: 2
    ports:
    - target: 5000
  backend:
    container_name: backend
    build: ./backend
    image: python-backend:latest
    ports: 
    - "5001:5001"