pipeline {
    agent any
    stages {
        stage('Demo Stage'){
            steps {
                sh "ls"
                sh "pwd"
                sh "mkdir pipeline_demo"
                sh "cd pipeline_demo"
                sh "ls"
            }
        }
    }
}