apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels: 
    app: nginx
spec:
  # This pod uses volume mounting
  volumes:
  - name: nginx-config              # Setting the volume name as nginx-config
    configMap:
      name: nginx-config            # referencing the contents of the ConfigMap
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: nginx-config            # referencing the volume name
      mountPath: /etc/nginx/  # specifying the mount location