version: "3.7"
services:
  flask-app:
    build: ./frontend
    image: flask-frontend:latest
    expose: 
    - 5500
    networks:
    - task-1
  nginx:
    image: nginx:latest
    volumes: 
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "80:80"
    networks:
    - task-1